apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-iamproxy
  namespace: kube-system
  labels:
    application: aws-iamproxy
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Cluster.InfrastructureAccount | getAWSAccountID }}:role/{{ .LocalID }}-app-aws-iamproxy"
