apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
  namespace: kube-system
data:
  aws-account-id: "{{accountID .Cluster.InfrastructureAccount}}"
  cluster-alias: "{{.Cluster.Alias}}"
  cluster-vpc-id: "{{.Cluster.ConfigItems.vpc_id}}"
  scalyr-team-token: "{{.Cluster.ConfigItems.scalyr_team_token}}"
  create-namespaces: "true"
  aws-available: "true"
  worker-role-arn: "arn:aws:iam::{{accountID .Cluster.InfrastructureAccount}}:role/{{.Cluster.LocalID}}-worker"
  oidc-provider-arn: "arn:aws:iam::{{accountID .Cluster.InfrastructureAccount}}:oidc-provider/{{.Cluster.LocalID}}.{{.Cluster.Alias}}.zalan.do"
  oidc-subject-prefix: "{{.Cluster.LocalID}}.{{.Cluster.Alias}}.zalan.do:sub: system:serviceaccount"
