apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-node-ready-controller
  namespace: kube-system
  labels:
    application: kube-node-ready-controller
spec:
  selector:
    matchLabels:
      application: kube-node-ready-controller
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: kube-node-ready-controller
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      serviceAccountName: kube-node-ready-controller
      dnsPolicy: Default
      tolerations:
      - key: node.kubernetes.io/role
        value: master
        effect: NoSchedule
      containers:
      - name: controller
        image: pierone.stups.zalan.do/teapot/kube-node-ready-controller:master-7
        resources:
          requests:
            cpu: {{.Cluster.ConfigItems.kube_node_ready_controller_cpu}}
            memory: {{.Cluster.ConfigItems.kube_node_ready_controller_memory}}
      nodeSelector:
        node.kubernetes.io/role: master
