apiVersion: v1
kind: Service
metadata:
  labels:
    application: kube-node-ready-controller
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  name: kube-node-ready-controller
  namespace: kube-system
spec:
  selector:
    application: kube-node-ready-controller
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
